### ISSUE TITLE
kleuren aanpassen van titel, topbar en navbar

### ISSUE THREAD

**Issue by jazzy80** [jazzy80/life-being#13]
Ik heb de volgende kleuren gevonden voor

* letters van links in topbar      -      #525a4a
* streepje onder links               -      #ca70a5
* letters hoofdtitel 'life being'    -      # f7b500

graag bovenstaande kleuren in CSS styles aanpassen

**Comment by jazzy80** [comment]
Dit is gedaan

**Comment by jazzy80** [comment]
Ik heb een nieuwe kleur (paars) gevonden

- accenten - streepje onder links - #bc6ff

Ik wil dit graag kunnen aanpassen in css Atom maar dat is voor mij niet werkzaam. 
Of texteditor; maar ik kan niet de update styles vinden. 
Kan je me helpen.

**Comment by ghost** [comment]
Gedaan, kijken morgen wel even (zie pull request)
