### ISSUE TITLE
blokken op be home

### ISSUE THREAD

**Issue by jazzy80** [jazzy80/life-being#19]
Aan de rechterzijde van de __be home_- _ pagina 
 3 blokken in 3 gelijke delen 
op 1/3 van de hoogte van beeldscherm 
met de volgende onderdelen:

- meest recente blogs
- inspire met poetry art
- meest recente gedicht

**Comment by ghost** [comment]
done zie pull request, most recent recipe verwijderd, en most recent blogs/poetry/poem verhuisd naar `Home`
