### ISSUE TITLE
sidebar met hartjes

### ISSUE THREAD

**Issue by jazzy80** [jazzy80/life-being#2]
sidebar met hartjes op pagina Life Being Insprirations
met menu van vijf onderwerpen
met submenu

**Comment by jazzy80** [comment]
aanvullende informatie:

- onder de titel _Vitality_ mogen vijf hartjes van boven  naar beneden

- menu met vijf buttons die verschijnen als je erover heen gaat met muis.

- buttons in een lichtere kleur dan de background. 

- buttons in rechthoek met ronde hoeken

**Comment by ghost** [comment]
![2022-02-24-004718_1920x1080_scrot](https://user-images.githubusercontent.com/52930665/155430117-4b0a3fbe-51af-48a8-a93d-012cf8b68719.png)

Hier even een eerste opzet van de sidebar, hartjes etc moeten er nog in

**Comment by jazzy80** [comment]
Wow, je hebt veel gedaan. Het ziet er mooi uit, mooie foto heb je uitgekozen. Fijn om te zien hoe iets eruit komt te zien. Ik kan daar nog geen concreet beeld van maken. Het is het nog niet helemaal, maar het is zo leuk om creatief bezig te zijn om te komen totdat het helemaal klopt. 
Zullen we daar zondag over praten? 

https://bronkracht.nl/

Deze site vind ik heel mooi. De topbar spreekt me aan met het logo Links en linken die naar pagina verwijzen. Mijn topbar mag dat ook hebben, dan mag de kleur goud worden als je erover heen gaat. De organische vormen tussen header en tekst gedeelte vind ik heel mooi. Dat zou ik ook graag zien op mijn website. Meer organische vormen in overgang en buttons etc. Ik zou niet weten hoe je dat maakt? 
ik zal op zoek gaan naar een sidebar die me aanspreekt. dan kom ik wellicht op goede ideeen. 
L.gr. Jessica 
    On Thursday, February 24, 2022, 12:50:07 AM GMT+1, Bowser-ai ***@***.***> wrote:  
 
 




Hier even een eerste opzet van de sidebar, hartjes etc moeten er nog in

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
