### ISSUE TITLE
aanpassing topbar en navbar

### ISSUE THREAD

**Issue by jazzy80** [jazzy80/life-being#34]
Werk voor jou in voorbereiding:

Graag de volgende aanpassingen aan topbar wat betreft volgorde (mocht het niet te veel werk zijn)

- Home, Life Being Inspirations, Life Being Atelier, Being child Illustrations. 

Graag de volgende aanpassing in de navbar

- Being Home, **Vitality**, Being Blogs, Poetry, Inspire etc. 

Graag de volgende aanpassingen wat betreft pagina aanmaak (mogelijk voor ons samen)

- Home
- Being Home - van Life Being Inspirations
- Vitality

**Comment by ghost** [comment]
Al die dingen kunnen in de admin worden aangepast, en vergt in principe geen werk, dat laatste onderdeel begrijp ik niet. Komt anders wel maandag
