### ISSUE TITLE
site paasend voor smartphone

### ISSUE THREAD

**Issue by jazzy80** [jazzy80/life-being#7]
gehele site passend maken voor smartphone gebruikers

als de letters/woorden op de 
* topbar niet meer leesbaar worden - gebruik maken van hamburger menu. 
* navbar niet meer leesbaar of passen - gebruik maken van hamburger menu

zorg dat de navbar op zijn plaats blijft bij compressie

**Comment by ghost** [comment]
Okee heb wat gedaan, prototype gemaakt voor een hamburger menu.

**Comment by ghost** [comment]
Voor het grootste gedeelte afgerond, uiteindelijk de hamburger menu in de lower navbar gezet omdat daar uiteindelijk meer linkjes komen
